//Collage:
const ACTION_CHANGE_USER_INPUT = "ACTION_CHANGE_USER_INPUT";
const ACTION_CHANGE_IMAGE = "ACTION_CHANGE_IMAGE";
const ACTION_CHANGE_TITTLE = "ACTION_CHANGE_TITTLE";
const ACTION_CHANGE_DESCRIPTION = "ACTION_CHANGE_DESCRIPTION";
const ACTION_CHANGE_COLLAGE = "ACTION_CHANGE_COLLAGE";

//Login:
const ACTION_CHANGE_AUTHORISED = "ACTION_CHANGE_AUTHORISED";
const ACTION_CHANGE_USERNAME = "ACTION_CHANGE_USERNAME";
const ACTION_CHANGE_PASSWORD = "ACTION_CHANGE_PASSWORD";
const ACTION_CHANGE_REDIRECT = "ACTION_CHANGE_REDIRECT";

//Navigation:
const ACTION_CHANGE_NAVIGATION_VISIBILITY =
  "ACTION_CHANGE_NAVIGATION_VISIBILITY";

//Sign Up:
const ACTION_CHANGE_SIGN_UP_USERNAME = "ACTION_CHANGE_SIGN_UP_USERNAME";
const ACTION_CHANGE_SIGN_UP_PASSWORD = "ACTION_CHANGE_SIGN_UP_PASSWORD";
const ACTION_CHANGE_SIGN_UP_PASSWORD_REPEAT =
  "ACTION_CHANGE_SIGN_UP_PASSWORD_REPEAT";
const ACTION_CHANGE_SIGN_UP_FIRST_NAME = "ACTION_CHANGE_SIGN_UP_FIRST_NAME";
const ACTION_CHANGE_SIGN_UP_LAST_NAME = "ACTION_CHANGE_SIGN_UP_LAST_NAME";
const ACTION_CHANGE_SIGN_UP_AGE = "ACTION_CHANGE_SIGN_UP_AGE";
const ACTION_CHANGE_SIGN_UP_REDIRECT = "ACTION_CHANGE_SIGN_UP_REDIRECT";
export {
  ACTION_CHANGE_AUTHORISED,
  ACTION_CHANGE_COLLAGE,
  ACTION_CHANGE_DESCRIPTION,
  ACTION_CHANGE_IMAGE,
  ACTION_CHANGE_NAVIGATION_VISIBILITY,
  ACTION_CHANGE_PASSWORD,
  ACTION_CHANGE_TITTLE,
  ACTION_CHANGE_USER_INPUT,
  ACTION_CHANGE_USERNAME,
  ACTION_CHANGE_REDIRECT,
  ACTION_CHANGE_SIGN_UP_USERNAME,
  ACTION_CHANGE_SIGN_UP_PASSWORD,
  ACTION_CHANGE_SIGN_UP_PASSWORD_REPEAT,
  ACTION_CHANGE_SIGN_UP_FIRST_NAME,
  ACTION_CHANGE_SIGN_UP_LAST_NAME,
  ACTION_CHANGE_SIGN_UP_AGE,
  ACTION_CHANGE_SIGN_UP_REDIRECT,
};
